title: Cocktail Cookbook
description: Its a cookbook, but for cocktails
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
